Revert "Push API: define push event on Service Worker."
This reverts r175672. It breaks the browser_tests compile
on Linux (and probably everywhere).

../../third_party/WebKit/Source/web/ServiceWorkerGlobalScopeProxy.cpp:103:74: error: no member named 'push' in namespace 'WebCore::EventTypeNames'
    m_workerGlobalScope->dispatchEvent(PushEvent::create(EventTypeNames::push, data));

TBR=mvanouwerkerk@chromium.org

Review URL: https://codereview.chromium.org/314373002

git-svn-id: svn://svn.chromium.org/blink/trunk@175677 bbb929c8-8fbe-4397-9dbb-9b2b20218538