Revert of Resolve screen.orientation.lock() promise with undefined. (https://codereview.chromium.org/400703003/)
Reason for revert:
Chromium unit tests fail to compile with this patch on Windows.

http://build.chromium.org/p/chromium.webkit/builders/Win%20Builder/builds/58418

Compilation error:
FAILED: ninja -t msvc -e environment.x86 -- C:\b\build\goma/gomacc "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\content\renderer\screen_orientation\content_unittests.screen_orientation_dispatcher_unittest.obj.rsp /c ..\..\content\renderer\screen_orientation\screen_orientation_dispatcher_unittest.cc /Foobj\content\renderer\screen_orientation\content_unittests.screen_orientation_dispatcher_unittest.obj /Fdobj\content\content_unittests.cc.pdb 
c:\b\build\slave\win-latest-rel\build\src\content\renderer\screen_orientation\screen_orientation_dispatcher_unittest.cc(121) :error C2259: 'content::MockLockOrientationCallback' : cannot instantiate abstract class
        due to following members:
        'void blink::WebLockOrientationCallback::onSuccess(void)' : is abstract
        c:\b\build\slave\win-latest-rel\build\src\third_party\webkit\public\platform\weblockorientationcallback.h(26) : see declaration of 'blink::WebLockOrientationCallback::onSuccess'


Original issue's description:
> Resolve screen.orientation.lock() promise with undefined.
> 
> This is following the current state of the specification.
> 
> BUG=162827
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=178406

TBR=abarth@chromium.org,mvanouwerkerk@chromium.org,mlamouri@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=162827

Review URL: https://codereview.chromium.org/400623004

git-svn-id: svn://svn.chromium.org/blink/trunk@178408 bbb929c8-8fbe-4397-9dbb-9b2b20218538