Revert of use gradient API that skips (deprecated) unitmapper param (https://codereview.chromium.org/293703003/)
Reason for revert:
Broke the build

../../third_party/WebKit/Source/platform/graphics/Gradient.cpp:247:147: error: cannot initialize a parameter of type 'SkUnitMapper *' with an lvalue of type 'uint32_t' (aka 'unsigned int')
            m_gradient = adoptRef(SkGradientShader::CreateRadial(m_p1.data(), m_r1, colors.data(), pos.data(), static_cast<int>(countUsed), tile, shouldDrawInPMColorSpace, &localMatrix));


Original issue's description:
> use gradient API that skips (deprecated) unitmapper param
> 
> NOTRY=True
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=174497

TBR=fmalita@chromium.org,schenney@chromium.org,reed@chromium.org,reed@google.com
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/295583007

git-svn-id: svn://svn.chromium.org/blink/trunk@174507 bbb929c8-8fbe-4397-9dbb-9b2b20218538