[gcc 4.x] Fix the broken build reported due to uninitialized |status| variable.
CL, https://codereview.chromium.org/1180013006, has introduced a loop breaking condition due to which
gcc 4.8 toolchain reports the following error:

In member function ‘bool blink::JPEGImageReader::decode(const blink::SharedBuffer&, bool)’:
Source/platform/image-decoders/jpeg/JPEGImageDecoder.cpp:554:81: error:
  ‘status’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  if (!m_info.output_scan_number && (scan > 1) && (status != JPEG_REACHED_EOI))
                                                         ^
We need to initialize the variable explicitly. Using value 0 is safe.

BUG=500567

R=noel@chromium.org, pkasting@chromium.org

Review URL: https://codereview.chromium.org/1189393002

git-svn-id: svn://svn.chromium.org/blink/trunk@197458 bbb929c8-8fbe-4397-9dbb-9b2b20218538