Revert of Add Unicode Variation Selector support to harfBuzzGetGlyph on Linux (patchset #2 id:20001 of https://codereview.chromium.org/1209043010/)
Reason for revert:
Breaks chromeos=1 builds on Linux.

../../third_party/WebKit/Source/platform/fonts/shaping/HarfBuzzFace.cpp:201:13: error: use of undeclared identifier 'hb_ot_font_set_funcs'
            hb_ot_font_set_funcs(hbFontData->m_hbOpenTypeFont);
            ^
1 error generated.


Original issue's description:
> Add Unicode Variation Selector support to harfBuzzGetGlyph on Linux
> 
> Most of the work to support Unicode Variation Selector was done in a
> separate CL[1], but it was not enabled for Linux due to crbug.com/462689.
> 
> With the bundled harfbuzz on Linux stabilized, this patch enables the
> Unicode Variation Selector support on Linux.
> 
> [1] https://codereview.chromium.org/1149693002
> 
> BUG=383580
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=198565

TBR=eae@chromium.org,behdad@google.com,drott@chromium.org,kojii@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=383580

Review URL: https://codereview.chromium.org/1229923003

git-svn-id: svn://svn.chromium.org/blink/trunk@198614 bbb929c8-8fbe-4397-9dbb-9b2b20218538