Revert of Revert of Remove prefixed Pointer Lock API. (https://codereview.chromium.org/424213007/)
Reason for revert:
Downstream tests have been updated to use unprefixed pointer lock in
https://codereview.chromium.org/438693003/

Original issue's description:
> Revert of Remove prefixed Pointer Lock API. (https://codereview.chromium.org/424093006/)
> 
> Reason for revert:
> The change broke several Chromium OS interactive_ui_tests:
> 
> ExtensionPointerLockAccessFail
> ExtensionPointerLockAccessPass
> EscapingMouseLock
> MouseLockSilentAfterTargetUnlock
> TestTabDoesntExitMouseLockOnSubFrameNavigation
> TestTabExitsMouseLockOnGoBack
> TestTabExitsMouseLockOnNavigation
> PointerLock_PointerLockLostWithFocus
> 
> that were using the prefixed API (""Uncaught TypeError: undefined is not a function").
> 
> See
> http://build.chromium.org/p/chromium.webkit/builders/Linux%20ChromiumOS%20Tests%20%282%29/builds/735/steps/interactive_ui_tests/logs/stdio
> 
> Original issue's description:
> > Remove prefixed Pointer Lock API.
> > 
> > The Pointer Lock API http://www.w3.org/TR/pointerlock has already been
> > implemented without prefix, this change removes the 'webkit' prefixed
> > API endpoints.
> > 
> > Intent to Deprecate and Remove:
> > https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/tN8fWRtG0MI
> > 
> > BUG=398457
> > 
> > Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=179172
> 
> TBR=abarth@chromium.org,scheib@chromium.org
> NOTREECHECKS=true
> NOTRY=true
> BUG=398457
> 
> Committed: https://src.chromium.org/viewvc/blink?view=rev&revision=179186

TBR=abarth@chromium.org,jchaffraix@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=398457

Review URL: https://codereview.chromium.org/437443005

git-svn-id: svn://svn.chromium.org/blink/trunk@179419 bbb929c8-8fbe-4397-9dbb-9b2b20218538