Revert "Switch LiveAudio to source provider solution."
This reverts commit 35099b760520c5b2b7e9efe77f5a941954e424df.

This CL does not build in the android_aosp configuration:

http://build.chromium.org/p/tryserver.chromium/builders/android_aosp/builds/12925

external/chromium_org/third_party/WebKit/Source/core/platform/mediastream/MediaStreamComponent.cpp:81:
error: undefined reference to 'WebCore::AudioBus::zero()'
collect2: error: ld returned 1 exit status

TBR=xians@chromium.org
BUG=257963

Review URL: https://codereview.chromium.org/23461051

git-svn-id: svn://svn.chromium.org/blink/trunk@157703 bbb929c8-8fbe-4397-9dbb-9b2b20218538